// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using personel_tayin_talebi_api.Data;

#nullable disable

namespace personel_tayin_talebi_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250609221529_add")]
    partial class add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonelRolleri", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("PersonelRolleri");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Adliye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolgeId")
                        .HasColumnType("int");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId");

                    b.ToTable("Adliyeler");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Bolge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZorunluHizmetSuresiYil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bolgeler");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.CalismaGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdliyeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AyrilmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("UnvanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdliyeId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("UnvanId");

                    b.ToTable("CalismaGecmisleri");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Duyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YayinTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Duyurular");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.IslemKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eylem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("IslemKayitlari");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HizmetPuani")
                        .HasColumnType("float");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SicilNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SicilNumarasi")
                        .IsUnique();

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Talep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtananAdliyeId")
                        .HasColumnType("int");

                    b.Property<string>("Gerekce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KararAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KararTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MevcutAdliyeId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("TalepDurumuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TalepTuruId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtananAdliyeId");

                    b.HasIndex("MevcutAdliyeId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("TalepDurumuId");

                    b.HasIndex("TalepTuruId");

                    b.ToTable("Talepler");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.TalepDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TalepDurumlari");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.TalepTercihi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdliyeId")
                        .HasColumnType("int");

                    b.Property<int>("SiraNumarasi")
                        .HasColumnType("int");

                    b.Property<int>("TalepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdliyeId");

                    b.HasIndex("TalepId");

                    b.ToTable("TalepTercihleri");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.TalepTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TalepTurleri");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.TayinDonemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TayinDonemleri");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Unvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unvanlar");
                });

            modelBuilder.Entity("PersonelRolleri", b =>
                {
                    b.HasOne("personel_tayin_talebi_api.Models.Personel", null)
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("personel_tayin_talebi_api.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Adliye", b =>
                {
                    b.HasOne("personel_tayin_talebi_api.Models.Bolge", "Bolge")
                        .WithMany()
                        .HasForeignKey("BolgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolge");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.CalismaGecmisi", b =>
                {
                    b.HasOne("personel_tayin_talebi_api.Models.Adliye", "Adliye")
                        .WithMany()
                        .HasForeignKey("AdliyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("personel_tayin_talebi_api.Models.Personel", "Personel")
                        .WithMany("CalismaGecmisleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("personel_tayin_talebi_api.Models.Unvan", "Unvan")
                        .WithMany()
                        .HasForeignKey("UnvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adliye");

                    b.Navigation("Personel");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.IslemKaydi", b =>
                {
                    b.HasOne("personel_tayin_talebi_api.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Talep", b =>
                {
                    b.HasOne("personel_tayin_talebi_api.Models.Adliye", "AtananAdliye")
                        .WithMany()
                        .HasForeignKey("AtananAdliyeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("personel_tayin_talebi_api.Models.Adliye", "MevcutAdliye")
                        .WithMany()
                        .HasForeignKey("MevcutAdliyeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("personel_tayin_talebi_api.Models.Personel", "Personel")
                        .WithMany("Talepler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("personel_tayin_talebi_api.Models.TalepDurumu", "TalepDurumu")
                        .WithMany()
                        .HasForeignKey("TalepDurumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("personel_tayin_talebi_api.Models.TalepTuru", "TalepTuru")
                        .WithMany()
                        .HasForeignKey("TalepTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtananAdliye");

                    b.Navigation("MevcutAdliye");

                    b.Navigation("Personel");

                    b.Navigation("TalepDurumu");

                    b.Navigation("TalepTuru");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.TalepTercihi", b =>
                {
                    b.HasOne("personel_tayin_talebi_api.Models.Adliye", "Adliye")
                        .WithMany()
                        .HasForeignKey("AdliyeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("personel_tayin_talebi_api.Models.Talep", "Talep")
                        .WithMany("TalepTercihleri")
                        .HasForeignKey("TalepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adliye");

                    b.Navigation("Talep");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Personel", b =>
                {
                    b.Navigation("CalismaGecmisleri");

                    b.Navigation("Talepler");
                });

            modelBuilder.Entity("personel_tayin_talebi_api.Models.Talep", b =>
                {
                    b.Navigation("TalepTercihleri");
                });
#pragma warning restore 612, 618
        }
    }
}
